version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    versioning-strategy: increase
    groups:
      hey-api:
        patterns:
          - '@hey-api/*'
      dev-dependencies-minor-patch:
        dependency-type: development
        update-types:
          - minor
          - patch
