version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    cooldown:
      # pnpm requires minimumReleaseAge of 1, so the value below should be 1 or more
      default-days: 1
    versioning-strategy: increase
    groups:
      eslint:
        patterns:
          - eslint
          - '@antfu/eslint-config'
          - 'eslint-plugin-*'
      standard-server:
        patterns:
          - '@standard-server/*'
      dev-dependencies-minor-patch:
        dependency-type: development
        exclude-patterns:
          - eslint
          - '@antfu/eslint-config'
          - 'eslint-plugin-*'
          - compression # inline
        update-types:
          - minor
          - patch
