import { defineMeta } from 'blume'

export default defineMeta({
  title: 'Adapters',
  pages: [
    'fetch-api',
    'node-http',
    'aws-lambda',
    'fastify',
    'websocket',
    'message-port',
    'astro',
    'browser',
    'cloudflare-workers',
    'electron',
    'elysia',
    'expo',
    'express',
    'h3',
    'hono',
    'next',
    'nuxt',
    'react-router',
    'solid-start',
    'svelte-kit',
    'tanstack-start',
    'web-workers',
    'worker-threads',
  ],
})
