name: 🐛 Bug report
description: Report an issue or a bug
labels: [bug, pending triage]
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out this bug report!
  - type: textarea
    id: bug-env
    attributes:
      label: Environment
      description: Package and Runtime version can be helpful to investigate issues
      placeholder: e.g. orpc@x.y.z, Node 20.x
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description:
        Please link to a minimal repository that reproduces the issue.
        A minimal repro is required unless the problem is obvious from your description.
        You can create one with [oRPC Playgrounds](https://orpc.unnoq.com/docs/playgrounds).
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description:
        Provide a clear, concise description of the bug.
        If you plan to submit a PR to fix it, mention that here. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: If applicable, add any other context about the problem here.
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Optional if provided reproduction. Please try not to insert an image but copy paste the log text.
      render: sh
