import type { PartialDeep } from '@orpc/shared'
import { RPCJsonSerializer } from '@orpc/client'
import { isPlainObject, stringifyJSON } from '@orpc/shared'

export interface OperationKeyPrefixOptions {
  /**
   * Prepended as the first element of the key when present.
   * Use this to avoid key conflicts when multiple router utils share the same client.
   */
  prefix?: string
}

export type OperationKeyOptions<TInput> = OperationKeyPrefixOptions & {
  input?: PartialDeep<TInput>
}

export type StructuredOperationKey
  = | [path: string[], options: { input?: unknown }]
    | [prefix: string, path: string[], options: { input?: unknown }]

const serializer = new RPCJsonSerializer()

/**
 * Sorts plain object keys recursively so the same input always
 * serializes to the same string, regardless of property order.
 */
function toStableJson(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(toStableJson)
  }

  if (isPlainObject(value)) {
    return Object.keys(value).sort().reduce((result, key) => {
      result[key] = toStableJson(value[key])
      return result
    }, {} as Record<string, unknown>)
  }

  return value
}

/**
 * Generate the structured form of an operation key, before serialization.
 *
 * The input is serialized to JSON-compatible values so the key
 * can be represented as a plain string.
 *
 * @see {@link https://orpc.dev/docs/integrations/nuxt#operation-key | Nuxt Integration - Operation Key}
 */
export function generateStructuredOperationKey<TInput>(
  path: string[],
  options: OperationKeyOptions<TInput> = {},
): StructuredOperationKey {
  return [
    ...options.prefix !== undefined ? [options.prefix] : [],
    path,
    {
      ...options.input !== undefined ? { input: toStableJson(serializer.serialize(options.input).json) } : {},
    },
  ] as StructuredOperationKey
}

/**
 * Generate a **full matching** string key for `useAsyncData` and related composables.
 *
 * Nuxt requires keys to be strings, so the structured key is serialized with `JSON.stringify`.
 *
 * @see {@link https://orpc.dev/docs/integrations/nuxt#operation-key | Nuxt Integration - Operation Key}
 */
export function generateOperationKey<TInput>(
  path: string[],
  options: OperationKeyOptions<TInput> = {},
): string {
  return stringifyJSON(generateStructuredOperationKey(path, options))
}

/**
 * Parse a string key back into its structured form.
 * Returns `undefined` if the key was not generated by `generateOperationKey`.
 *
 * @see {@link https://orpc.dev/docs/integrations/nuxt#operation-key | Nuxt Integration - Operation Key}
 */
export function parseOperationKey(key: string): StructuredOperationKey | undefined {
  try {
    const parsed = JSON.parse(key)

    if (!Array.isArray(parsed) || parsed.length < 2 || parsed.length > 3) {
      return undefined
    }

    const [prefix, path, options] = parsed.length === 3 ? parsed : [undefined, ...parsed]

    if (parsed.length === 3 && typeof prefix !== 'string') {
      return undefined
    }

    if (!Array.isArray(path) || !path.every(segment => typeof segment === 'string') || !isPlainObject(options)) {
      return undefined
    }

    return parsed as StructuredOperationKey
  }
  catch {
    return undefined
  }
}
