name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint_and_typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6

      - run: pnpm i

      - run: pnpm run lint

      - run: pnpm run type:check

      - run: pnpm run docs:validate

  test_matrix:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    strategy:
      matrix:
        node-version: [26, 24, 22, 20]
      fail-fast: false
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6

      - run: pnpm runtime set node ${{ matrix.node-version }}
      - run: pnpm runtime set bun 1

      - run: pnpm i

      - run: pnpm run test:coverage
        env:
          REDIS_URL: redis://localhost:6379
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}

      - uses: codecov/codecov-action@v7
        # Upstash tests are skipped in node 26 - so we prefer node 24
        # TODO: use node 26
        if: matrix.node-version == 24
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  publish_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6

      - run: pnpm i

      - run: pnpm --filter='./packages/*' run -r build

      - run: pnpm exec pkg-pr-new publish './packages/*' --pnpm --compact --template './playgrounds/*'
