/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
// Generated by scripts/sync-sponsors.ts from https://raw.githubusercontent.com/middleapi/static/refs/heads/main/ads.json — do not edit.

export default [
  {
    "name": "ScreenshotOne",
    "description": "The screenshot API for developers",
    "logo": "https://github.com/screenshotone.png",
    "href": "https://screenshotone.com?ref=orpc&utm_source=orpc&utm_medium=sponsor",
    "weight": 1
  },
  {
    "name": "MisskeyHQ",
    "description": "Decentralized microblogging SNS born on Earth",
    "logo": "https://github.com/MisskeyIO.png",
    "href": "https://misskey.io?ref=orpc&utm_source=orpc&utm_medium=sponsor",
    "weight": 0.5
  },
  {
    "name": "Your Product",
    "description": "Advertise here, contact us to get started",
    "logo": "data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 24 24%22 fill=%22none%22 stroke=%22%238b8b8b%22 stroke-width=%222%22 stroke-linecap=%22round%22 stroke-linejoin=%22round%22%3E%3Cpath d=%22m3 11 18-5v12L3 14v-3z%22/%3E%3Cpath d=%22M11.6 16.8a3 3 0 1 1-5.8-1.6%22/%3E%3C/svg%3E",
    "href": "mailto:dinwwwh@gmail.com?subject=Advertise%20on%20middleapi%2Forpc&body=Hi%2C%0A%0AI%20want%20to%20advertise%20my%20product%20on%20middleapi%2Forpc.%0A%0AProduct%20name%3A%20%0AWebsite%3A%20%0ALogo%20URL%3A%20",
    "weight": 0.5
  }
]
