/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
// Generated by scripts/sync-sponsors.ts from https://raw.githubusercontent.com/middleapi/static/refs/heads/main/sponsors.json — do not edit.

export default [
  {
    "position": 1,
    "name": "ScreenshotOne.com",
    "description": "The screenshot API for developers",
    "logo": "https://avatars.githubusercontent.com/u/97035603?v=4",
    "href": "https://screenshotone.com/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "",
    "background": {
      "light": "#f7f5ff",
      "dark": "#303147"
    }
  },
  {
    "position": 2,
    "name": "Yuzu",
    "description": "We're hiring NYC based engineers",
    "logo": "https://avatars.githubusercontent.com/u/102488956?v=4",
    "href": "https://yuzu.health/careers?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "background": {
      "light": "#fdf5f3",
      "dark": "#3d302e"
    }
  },
  {
    "position": 4,
    "name": "MisskeyHQ",
    "description": "Decentralized microblogging SNS born on Earth",
    "logo": "https://github.com/MisskeyIO.png",
    "href": "https://misskey.io/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "background": {
      "light": "#f8faf0",
      "dark": "#313a2e"
    }
  }
]
