/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
// Generated by scripts/sync-sponsors.ts from https://raw.githubusercontent.com/middleapi/static/refs/heads/main/sponsors.json — do not edit.

export default [
  {
    "name": "ScreenshotOne.com",
    "login": "screenshotone",
    "avatar": "https://avatars.githubusercontent.com/u/97035603?v=4",
    "link": "https://screenshotone.com/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "",
    "tierTitle": "Special Sponsor",
    "tierLevel": 5
  },
  {
    "name": "Yuzu",
    "login": "yuzu-health",
    "avatar": "https://avatars.githubusercontent.com/u/102488956?v=4",
    "link": "https://yuzu.health/careers?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Premium Sponsor",
    "tierLevel": 4
  },
  {
    "name": "MisskeyHQ",
    "login": "SanMurakami",
    "avatar": "https://github.com/MisskeyIO.png",
    "link": "https://misskey.io/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Premium Sponsor",
    "tierLevel": 4
  },
  {
    "name": "LN Markets",
    "login": "ln-markets",
    "avatar": "https://avatars.githubusercontent.com/u/70597625?v=4",
    "link": "https://lnmarkets.com/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Organization Sponsor",
    "tierLevel": 3
  },
  {
    "name": "Reece McDonald",
    "login": "hrmcdonald",
    "avatar": "https://avatars.githubusercontent.com/u/39349270?v=4",
    "link": "https://github.com/hrmcdonald?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Sponsor",
    "tierLevel": 2
  },
  {
    "name": "あわわわとーにゅ",
    "login": "u1-liquid",
    "avatar": "https://avatars.githubusercontent.com/u/17376330?u=de3353804be889f009f7e0a1582daf04d0ab292d&v=4",
    "link": "https://soymilk.party/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Sponsor",
    "tierLevel": 2
  },
  {
    "name": "nk",
    "login": "nicognaW",
    "avatar": "https://avatars.githubusercontent.com/u/66731869?u=4699bda3a9092d3ec34fbd959450767bcc8b8b6d&v=4",
    "link": "https://github.com/nicognaW?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Sponsor",
    "tierLevel": 2
  },
  {
    "name": "supastarter",
    "login": "supastarter",
    "avatar": "https://avatars.githubusercontent.com/u/110960143?v=4",
    "link": "https://supastarter.dev/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Sponsor",
    "tierLevel": 2
  },
  {
    "name": "Dexter Miguel",
    "login": "divmgl",
    "avatar": "https://avatars.githubusercontent.com/u/5452298?u=645993204be8696c085ecf0d228c3062efe2ed65&v=4",
    "link": "https://github.com/divmgl?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Sponsor",
    "tierLevel": 2
  },
  {
    "name": "herrfugbaum",
    "login": "herrfugbaum",
    "avatar": "https://avatars.githubusercontent.com/u/12859776?u=644dc1666d0220bc0468eb0de3c56b919f635b16&v=4",
    "link": "https://github.com/herrfugbaum?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Sponsor",
    "tierLevel": 2
  },
  {
    "name": "Ryota Murakami",
    "login": "ryota-murakami",
    "avatar": "https://avatars.githubusercontent.com/u/5501268?u=599389e03340734325726ca3f8f423c021d47d7f&v=4",
    "link": "https://laststance.io/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Sponsor",
    "tierLevel": 2
  },
  {
    "name": "David Cramer",
    "login": "dcramer",
    "avatar": "https://avatars.githubusercontent.com/u/23610?v=4",
    "link": "https://cra.mr/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Sponsor",
    "tierLevel": 2
  },
  {
    "name": "Valerii Petryniak",
    "login": "valerii15298",
    "avatar": "https://avatars.githubusercontent.com/u/44531564?u=88ac74d9bacd20401518441907acad21063cd397&v=4",
    "link": "https://valerii15298.github.io/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Sponsor",
    "tierLevel": 2
  },
  {
    "name": "Valerii Strilets",
    "login": "letstri",
    "avatar": "https://avatars.githubusercontent.com/u/13253748?u=c7b10399ccc8f8081e24db94ec32cd9858e86ac3&v=4",
    "link": "https://letstri.dev/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Sponsor",
    "tierLevel": 2
  },
  {
    "name": "Kyle Mistele",
    "login": "K-Mistele",
    "avatar": "https://avatars.githubusercontent.com/u/18430555?u=3afebeb81de666e35aaac3ed46f14159d7603ffb&v=4",
    "link": "https://blacklight.sh/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Sponsor",
    "tierLevel": 2
  },
  {
    "name": "christ12938",
    "login": "christ12938",
    "avatar": "https://avatars.githubusercontent.com/u/25758598?v=4",
    "link": "https://github.com/christ12938?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Sponsor",
    "tierLevel": 2
  },
  {
    "name": "Ryan Soderberg",
    "login": "Ryanjso",
    "avatar": "https://avatars.githubusercontent.com/u/39172778?u=5ed913c31d57e7221b75784abcad48c7ebddde27&v=4",
    "link": "https://github.com/Ryanjso?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Sponsor",
    "tierLevel": 2
  },
  {
    "name": "shota",
    "login": "itigoore01",
    "avatar": "https://avatars.githubusercontent.com/u/11831107?u=c976a6dc7e055eb026304c46c99100ed22b0c8e0&v=4",
    "link": "https://github.com/itigoore01?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Sponsor",
    "tierLevel": 2
  },
  {
    "name": "Ellis Driscoll",
    "login": "ellis-driscoll",
    "avatar": "https://avatars.githubusercontent.com/u/70685966?u=c5f95bc33b5991d9744abe00052542e4a2ed3cb9&v=4",
    "link": "https://github.com/ellis-driscoll?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Sponsor",
    "tierLevel": 2
  },
  {
    "name": "Hoang Nguyen",
    "login": "hoangbn",
    "avatar": "https://avatars.githubusercontent.com/u/38968280?u=c90084c6de65c56facabab7ba13a72a49ddbc3e4&v=4",
    "link": "https://github.com/hoangbn?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Sponsor",
    "tierLevel": 2
  },
  {
    "name": "Orestis Ioannou",
    "login": "guest-ac41de3b",
    "avatar": "https://images.opencollective.com/guest-ac41de3b/avatar/460.png",
    "link": "https://opencollective.com/guest-ac41de3b?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Sponsor",
    "tierLevel": 2
  },
  {
    "name": "David Walsh",
    "login": "rhinodavid",
    "avatar": "https://avatars.githubusercontent.com/u/5778036?u=b5521f07d2f88c3db2a0dae62b5f2f8357214af0&v=4",
    "link": "https://github.com/rhinodavid?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Backer",
    "tierLevel": 1
  },
  {
    "name": "IPv4Addr",
    "login": "IPv4Addr",
    "avatar": "https://avatars.githubusercontent.com/u/100147665?u=59996b72f69bb53063cb7e9ff8b8f898616cd94d&v=4",
    "link": "https://github.com/IPv4Addr?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Backer",
    "tierLevel": 1
  },
  {
    "name": "Robbe Vaes",
    "login": "Robbe95",
    "avatar": "https://avatars.githubusercontent.com/u/44748019?u=e0232402c045ad4eac7cbd217f1f47e083103b89&v=4",
    "link": "https://robbevaes.be/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Backer",
    "tierLevel": 1
  },
  {
    "name": "Aidan Sunbury",
    "login": "aidansunbury",
    "avatar": "https://avatars.githubusercontent.com/u/64103161?v=4",
    "link": "https://github.com/aidansunbury?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Backer",
    "tierLevel": 1
  },
  {
    "name": "soonoo",
    "login": "soonoo",
    "avatar": "https://avatars.githubusercontent.com/u/5436405?u=5d0b4aa955c87e30e6bda7f0cccae5402da99528&v=4",
    "link": "https://github.com/soonoo?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Backer",
    "tierLevel": 1
  },
  {
    "name": "Kevin Porten",
    "login": "kporten",
    "avatar": "https://avatars.githubusercontent.com/u/1839345?u=dc2263d5cfe0d927ce1a0be04a1d55dd6b55405c&v=4",
    "link": "https://kevinporten.dev/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Backer",
    "tierLevel": 1
  },
  {
    "name": "Denis",
    "login": "pumpkinlink",
    "avatar": "https://avatars.githubusercontent.com/u/11864620?u=5f47bbe6c65d0f6f5cf011021490238e4b0593d0&v=4",
    "link": "https://github.com/pumpkinlink?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Backer",
    "tierLevel": 1
  },
  {
    "name": "Christopher Kapic",
    "login": "christopher-kapic",
    "avatar": "https://avatars.githubusercontent.com/u/59740769?u=e7ad4b72b5bf6c9eb1644c26dbf3332a8f987377&v=4",
    "link": "https://github.com/christopher-kapic?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Backer",
    "tierLevel": 1
  },
  {
    "name": "Tom Ballinger",
    "login": "thomasballinger",
    "avatar": "https://avatars.githubusercontent.com/u/458879?u=4b045ac75d721b6ac2b42a74d7d37f61f0414031&v=4",
    "link": "http://ballingt.com/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Backer",
    "tierLevel": 1
  },
  {
    "name": "Sam",
    "login": "SSam0419",
    "avatar": "https://avatars.githubusercontent.com/u/102863520?u=3c89611f549d5070be232eb4532f690c8f2e7a65&v=4",
    "link": "https://lee-sam.com/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Backer",
    "tierLevel": 1
  },
  {
    "name": "Titoine",
    "login": "Titoine",
    "avatar": "https://avatars.githubusercontent.com/u/3514286?u=1bb1e86b0c99c8a1121372e56d51a177eea12191&v=4",
    "link": "https://github.com/Titoine?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Backer",
    "tierLevel": 1
  },
  {
    "name": "Igor Makowski",
    "login": "Mnigos",
    "avatar": "https://avatars.githubusercontent.com/u/56691628?u=ee8c879478f7c151b9156aef6c74243fa3e247a8&v=4",
    "link": "https://rigtch.fm/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Backer",
    "tierLevel": 1
  },
  {
    "name": "hanayashiki",
    "login": "hanayashiki",
    "avatar": "https://avatars.githubusercontent.com/u/26056783?u=06c3b9205a16fd41a871e82da1cc2a09306d53f5&v=4",
    "link": "https://blog.cwang.io/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Backer",
    "tierLevel": 1
  },
  {
    "name": "Lev Dubinets",
    "login": "ldub",
    "avatar": "https://avatars.githubusercontent.com/u/3114081?u=f547f5d5012cab54851f1b1ad72d10e537f78fc2&v=4",
    "link": "https://dubinets.io/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Backer",
    "tierLevel": 1
  },
  {
    "name": "Kelly Peilin Chan",
    "login": "mr-kelly",
    "avatar": "https://avatars.githubusercontent.com/u/520852?u=6b0f7105f694e7b5cacf410a3f04c7044b469dc8&v=4",
    "link": "https://kellychan.im/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Backer",
    "tierLevel": 1
  },
  {
    "name": "Guy Ariely",
    "login": "guyariely",
    "avatar": "https://avatars.githubusercontent.com/u/42813496?u=edb6b7f563bf28e160a290832e7da57c0506f8ca&v=4",
    "link": "https://guyariely.com/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Backer",
    "tierLevel": 1
  },
  {
    "name": "PaulSenon",
    "login": "PaulSenon",
    "avatar": "https://avatars.githubusercontent.com/u/19531087?u=6385741eb91d200b8c513ec6045482e301767ca6&v=4",
    "link": "https://paulsenon.com/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Backer",
    "tierLevel": 1
  },
  {
    "name": "Alex",
    "login": "piscis",
    "avatar": "https://avatars.githubusercontent.com/u/326163?u=b245f368bd940cf51d08c0b6bf55f8257f359437&v=4",
    "link": "https://piscis.dev/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Backer",
    "tierLevel": 1
  },
  {
    "name": "Andrey Gubanov",
    "login": "finom",
    "avatar": "https://avatars.githubusercontent.com/u/1082083?u=c5f2daf7ebece498e85c83367bb37b4e10e2649d&v=4",
    "link": "https://opensource.gubanov.eu/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Backer",
    "tierLevel": 1
  },
  {
    "name": "Maxie",
    "login": "MrMaxie",
    "avatar": "https://avatars.githubusercontent.com/u/3857836?u=5e6b57973d4385d655663ffdd836e487856f2984&v=4",
    "link": "https://maxie.dev/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Zuplo",
    "login": "zuplo",
    "avatar": "https://avatars.githubusercontent.com/u/85497839?v=4",
    "link": "https://zuplo.com/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "motopods",
    "login": "motopods",
    "avatar": "https://avatars.githubusercontent.com/u/58200641?v=4",
    "link": "https://github.com/motopods?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Francisco Hermida",
    "login": "franciscohermida",
    "avatar": "https://avatars.githubusercontent.com/u/483242?u=bbcbc80eb9d8781ff401f7dafc3b59cd7bea0561&v=4",
    "link": "https://github.com/franciscohermida?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Théo LUDWIG",
    "login": "theoludwig",
    "avatar": "https://avatars.githubusercontent.com/u/25207499?u=a6a9653725a2f574c07893748806668e0598cdbe&v=4",
    "link": "https://theoludwig.fr/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Abhay Ramesh",
    "login": "abhay-ramesh",
    "avatar": "https://avatars.githubusercontent.com/u/66196314?u=c5c2b0327b26606c2efcfaf17046ab18c3d25c57&v=4",
    "link": "https://abhayramesh.com/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "shr.ink oü",
    "login": "shr-ink",
    "avatar": "https://avatars.githubusercontent.com/u/139700438?v=4",
    "link": "https://github.com/shr-ink?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "0x4e32",
    "login": "johngerome",
    "avatar": "https://avatars.githubusercontent.com/u/2002000?u=505e54608466ab53754f702973687b04c6424c1f&v=4",
    "link": "https://0x4e32.dev/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Ryuz",
    "login": "ryuzdev",
    "avatar": "https://avatars.githubusercontent.com/u/196539378?u=d38374588d219b6748b16406982f6559411466d4&v=4",
    "link": "https://github.com/ryuzdev?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "happyboy",
    "login": "happyboy2022",
    "avatar": "https://avatars.githubusercontent.com/u/103669586?u=65b49c4b893ed3703909fbb3a7a22313f3f9c121&v=4",
    "link": "https://github.com/happyboy2022?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "yicchi",
    "login": "YiCChi",
    "avatar": "https://avatars.githubusercontent.com/u/86967274?u=6c2756f09fe15dd94d572f560e979cd157982852&v=4",
    "link": "https://github.com/YiCChi?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Saksham",
    "login": "cloudycotton",
    "avatar": "https://avatars.githubusercontent.com/u/168998965?u=9b9634a5aed66a51c1b880663272725b00b92b14&v=4",
    "link": "https://saksham.work/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Roman Hrynevych",
    "login": "hrynevychroman",
    "avatar": "https://avatars.githubusercontent.com/u/82209198?u=1a1d111ab3d589855b9cc8a7fefb1b5c6a4fbbaf&v=4",
    "link": "https://hrynevych.dev/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "rokitg",
    "login": "rokitgg",
    "avatar": "https://avatars.githubusercontent.com/u/125133357?u=06c74aefaa2236b06a2e5fba5a5c612339f45912&v=4",
    "link": "https://github.com/rokitgg?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Omar Khatib",
    "login": "omarkhatibgg",
    "avatar": "https://avatars.githubusercontent.com/u/9054278?u=afbba7331b85c51b8eee4130f5fd31b1017dc919&v=4",
    "link": "http://khatib.gg/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Yu-Sabo",
    "login": "YuSabo90002",
    "avatar": "https://avatars.githubusercontent.com/u/13120582?v=4",
    "link": "https://github.com/YuSabo90002?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Bapusaheb Patil",
    "login": "bapspatil",
    "avatar": "https://avatars.githubusercontent.com/u/16699418?u=6d9d8e0a64a6f91ca1c4d559c72d931172bdcbbd&v=4",
    "link": "https://bapspatil.com/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "grim",
    "login": "ripgrim",
    "avatar": "https://avatars.githubusercontent.com/u/75869731?u=b17c42ec2309552fdb822a86b25a2f99146a4d72&v=4",
    "link": "https://tripwire.sh/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Nelson Lai",
    "login": "nelsonlaidev",
    "avatar": "https://avatars.githubusercontent.com/u/75498339?u=2fc0e0b95dd184c5ffb744df977cb15a18b60672&v=4",
    "link": "https://nelsonlai.dev/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Lê Cao Nguyên",
    "login": "nguyenlc1993",
    "avatar": "https://avatars.githubusercontent.com/u/13871971?u=83c8b69d9e35b589c4e1f066cc113b1d9461386f&v=4",
    "link": "https://github.com/nguyenlc1993?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Robert Soriano",
    "login": "wobsoriano",
    "avatar": "https://avatars.githubusercontent.com/u/13049130?u=6d72104182e7c9ed25934815313fb69107332111&v=4",
    "link": "https://robsoriano.com/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Andrew Peters",
    "login": "andrewpeters9",
    "avatar": "https://avatars.githubusercontent.com/u/36251325?v=4",
    "link": "https://github.com/andrewpeters9?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Ryan Vogel",
    "login": "R44VC0RP",
    "avatar": "https://avatars.githubusercontent.com/u/89211796?u=1857347b9787d8d8a7ea5bfc333f96be92d5a683&v=4",
    "link": "https://ryan.ceo/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "SKostyukovich",
    "login": "SKostyukovich",
    "avatar": "https://avatars.githubusercontent.com/u/10700067?v=4",
    "link": "https://github.com/SKostyukovich?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Peter Adam",
    "login": "peter-adam-dy",
    "avatar": "https://avatars.githubusercontent.com/u/132129459?u=4f3dbbb3b443990b56acb7d6a5d11ed2c555f6db&v=4",
    "link": "https://github.com/peter-adam-dy?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Fabworks",
    "login": "FabworksHQ",
    "avatar": "https://avatars.githubusercontent.com/u/160179500?v=4",
    "link": "https://fabworks.com/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Novak Antonijevic",
    "login": "NovakAnton",
    "avatar": "https://avatars.githubusercontent.com/u/157126729?u=ae49fa22292d55c0434ff0ca008206155b18663b&v=4",
    "link": "https://github.com/NovakAnton?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Laduni Estu Syalwa",
    "login": "laduniestu",
    "avatar": "https://avatars.githubusercontent.com/u/44757637?u=a2fc1ea8f7d827a96721176f79d30592d1c48059&v=4",
    "link": "https://dun.gg/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Chen, Zhi-Yuan",
    "login": "yukimotochern",
    "avatar": "https://avatars.githubusercontent.com/u/20896173?u=945c33fc21725e4d566a0d02afc54b136ca1d67a&v=4",
    "link": "https://github.com/yukimotochern?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Illarion Koperski",
    "login": "illarionvk",
    "avatar": "https://avatars.githubusercontent.com/u/5012724?u=7cfa13652f7ac5fb3c56d880e3eb3fbe40c3ea34&v=4",
    "link": "https://illarionvk.com/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Anees Iqbal",
    "login": "steelbrain",
    "avatar": "https://avatars.githubusercontent.com/u/4278113?u=22b80b5399eed68ac76cd58b02961b0481f1db11&v=4",
    "link": "https://aneesiqbal.ai/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Sefa Eyeoglu",
    "login": "Scrumplex",
    "avatar": "https://avatars.githubusercontent.com/u/11587657?u=ab503582165c0bbff0cca47ce31c9450bb1553c9&v=4",
    "link": "https://scrumplex.net/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "natt",
    "login": "nattstack",
    "avatar": "https://avatars.githubusercontent.com/u/31426677?u=fa9dbb8b3e66eb0ea3c88db5dc07f31c8c5418fe&v=4",
    "link": "https://natt.so/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Adam Tkaczyk",
    "login": "ChromeGG",
    "avatar": "https://avatars.githubusercontent.com/u/39050595?u=a58ca6042a6950e94e6e92442db76ef584279bc0&v=4",
    "link": "https://tkaczyk.dev/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "plancraft",
    "login": "plancraft",
    "avatar": "https://avatars.githubusercontent.com/u/46482287?v=4",
    "link": "https://plancraft.com/?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  },
  {
    "name": "Nicholas",
    "login": "Nic13Gamer",
    "avatar": "https://avatars.githubusercontent.com/u/54724556?u=56a7ab430ce7a80d648ab6eba051d454a818ed0b&v=4",
    "link": "https://github.com/Nic13Gamer?ref=middleapi&utm_source=middleapi&utm_medium=sponsor",
    "rel": "sponsored",
    "tierTitle": "Past Sponsor",
    "tierLevel": 0
  }
]
